INSERT INTO Usuarios (Nombres, Apellidos, DNI, Sexo, Username, Pass, Picture, Cargo, Estado) VALUES
('Erick', 'Huamani Mendoza', 45432345, 'Masculino', 'erick', 'erick', 'dsfk', 'Administrador', 'Activo'),
('Jimmy', 'Huamani Mendoza', 76431075, 'Masculino', 'jimmy', 'jimmy', 'sldf', 'Administrador', 'Activo');


INSERT INTO Clientes (Nombres, Apellidos, DNI, Sexo, TipoCliente, Picture, Estado, FechaRegistrado)
VALUES
('jimmy', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('erick', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('pedro', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('jorge', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('luis', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('richar', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('dinesh', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('carlos', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('maria', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('kevo', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('jasmin', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('kucero', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('massiel', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('rosa', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('roni', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('mijael', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('jenny', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('jhonatan', 'huamani mendoza', 12345678, 'Masculino', 'Universitario', 'sjfdslf', default, default),
('jimmy', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('erick', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('pedro', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('jorge', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('luis', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('richar', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('dinesh', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('carlos', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('maria', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('kevo', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('jasmin', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('kucero', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('massiel', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('rosa', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('roni', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('mijael', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('jenny', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('jhonatan', 'huamani mendoza', 12345678, 'Masculino', 'Escolar', 'sjfdslf', default, default),
('jimmy', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('erick', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('pedro', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('jorge', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('luis', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('richar', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('dinesh', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('carlos', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('maria', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('kevo', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('jasmin', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('kucero', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('massiel', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('rosa', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('roni', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('mijael', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('jenny', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default),
('jhonatan', 'huamani mendoza', 12345678, 'Masculino', 'Urbano', 'sjfdslf', default, default);
